on: [push]
name: Sharkey.rs CI
env:
  BLAHAJ_API_TOKEN: ${{ secrets.BLAHAJ_API_TOKEN }}
jobs:
  build_and_test:
    name: Sharkey.rs CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "Run tests."
        uses: actions-rs/cargo@v1
        with:
          command: test